[project]
name = "repl-nix-comprehensiveuibuilder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "openpyxl>=3.1.5",
    "plotly>=5.24.1",
    "pytz>=2024.2",
    "streamlit>=1.39.0",
    "trafilatura>=1.12.2",
]
